fschmid_dev_sso_service:
  cookies:
    shared_cookie_domain: YOUR_SHARED_COOKIE_DOMAIN (.example.wip)
  user_provider:
    url: 'https://user.example.wip/user-profile'
    user: App\\Entity\\User
  logout: app_logout